### ISSUE TITLE
Semantic versioning for first release 

### ISSUE THREAD

**Issue by iotFab** [awslabs/smart-product-solution#18]
How do I know when to release 1.0.0?

If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.
https://semver.org/

**Comment by rakshb** [comment]
@iotFab will be added to backlog and reviewed for a future release
