### ISSUE TITLE
Deploying 2 times the solution will fail due to CodeCommit repository already present

### ISSUE THREAD

**Issue by iotFab** [awslabs/smart-product-solution#21]
The clean up of codeCommit is skipped when deleting the stack. 
Running the stack a second time will fail due to codeCommit repository existing with the same name. 

2 options : 
- Force the deletion of code commit 
OR 
- Add a variable string at the end of this ressource name. 

Thank you, 
Fabian

**Comment by iotFab** [comment]
An option to resolve that would be to change the default variable name for CodeCommit Repository Name.
The result of this would be like the second option which is done automatically.
This will smooth the process in case of failure in first attempt.

**Comment by gsingh04** [comment]
Thank you for reporting this behavior. Please feel free to open PR and we can investigate the behavior you are aiming for.
