### ISSUE TITLE
Version out of sync 

### ISSUE THREAD

**Issue by iotFab** [awslabs/smart-product-solution#22]
Version used in the website is 1.0.2. 
https://aws.amazon.com/solutions/implementations/smart-product-solution/ 

Was able to launch version on the website with few clicks... The demo in GIT miss some documentation to succeed the basic deployment. 
Do you have ETA to make the working version available in GIT with the correct instructions to reproduce ?

**Comment by gsingh04** [comment]
Hello,

Can you please share details of what issue you are facing. Our solution artifacts should be same everywhere.

**Comment by iotFab** [comment]
I have the website proposing the solution. 
Click, click -> works 

I try first to do that from Git Repository. It was not producing the same result. It was even failing to deploy completely. 
I guess you have some difference somewhere that allow to have a clean and easy deployment from the website OR some missing steps that are not documented that I miss when trying to deploy the solution. 

To give you details about what is failing I would have to follow your docs on this Git Repo in order to provide you the error. 
The amount of time allocated to test this solution is over, I would prefer to test a working solution ;)
But it's no more a critical requirement as the website is working to provide some example.
