### ISSUE TITLE
I can't unzip "reference.tar.gz" on Raspberry Pi.

### ISSUE THREAD

**Issue by nbc-pet-task** [awslabs/smart-product-solution#4]
I try set up a raspberry Pi device for Smart Product Solution.

To download and install the file neccessary to simulate a smart product..

$ curl -O https://smart-product-test-scripts.s3.amazonaws.com/reference.tar.gz
$ tar xvfz reference.tar.gz

but It was not working

I got the message blow.

pi@raspberrypi: ~ /reference $ curl -O https://smart-product-test-scripts.s3.amazonaws.com/reference.tar.gz
 Total    Received   Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   243    0   243    0     0    264      0 --:--:-- --:--:-- --:--:--   264
pi@raspberrypi:~/reference $ tar xvfz reference.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
pi@raspberrypi:~ /reference $ cat reference.tar.gz

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message >Access Denied</Message><RequestId>FC26EB0C2A3AD414</RequestId><HostId>VAuRNfzESUlYVZhKIUjuHAFRJQPaqEyAkUTjboZA90O0KPZkLXq/92pm6cKo9kDQy/WSUsxyv0w=</HostId></Error>

Help me plz.

**Comment by beomseoklee** [comment]
@nbc-pet-task I'm sorry for your inconvenience, and it should be available now.

**Comment by nbc-pet-task** [comment]
Thanks a lot :)
