### ISSUE TITLE
Error using mosquitto_pub on Raspberry Pi and playing simulator.js

### ISSUE THREAD

**Issue by nbc-pet-task** [awslabs/smart-product-solution#5]
I am watching and following a Youtube video and tutorial.
https://www.youtube.com/watch?v=kgXYO5Iqklo&t=1894s
https://docs.aws.amazon.com/solutions/latest/smart-product-solution/deployment.html

However
I got a issue follow..

pi@raspberrypi:~/aws_SmartProductSolutionsSample $ mosquitto_pub --cafile root.cert --cert deviceCertAndCACert.crt --key deviceCert.key -p 8883 -q 1 -t foo/bar -i anyclientID --tls-version tlsv1.2 -m "Hello" -d -h a1inzd6lczlz6f-ats.iot.us-east-1.amazonaws.com
Client anyclientID sending CONNECT
OpenSSL Error: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Error: Success

So I can't running simulator.js below..
![image](https://user-images.githubusercontent.com/54093794/76813057-1fda1800-683a-11ea-9e79-b888aa43f9c0.png)

Did I do something wrong?

**Comment by nbc-pet-task** [comment]
I did reinstall mosquitto latest version. so I got same message on your video.

$ mosquitto_pub --cafile root.cert --cert deviceCertAndCACert.crt --key deviceCert.key -p 8883 -q 1 -t foo/bar -i anyclientID --tls-version tlsv1.2 -m "Hello" -d -h a1inzd6lczlz6f-ats.iot.us-east-1.amazonaws.com
Client anyclientID sending CONNECT
Error: The connection was lost.

But when I run simulator I got same issue.

~/simulator $ sed -i -e 's/REPLACE_HERE/123456789-abcde/g' config.js
~/simulator $ npm start

> smart-product-demo-simulator@0.0.1 start /home/pi/simulator
> node simulator.js

Connecting to AWS IoT...

????? Stopping........

**Comment by nbc-pet-task** [comment]
Um..
I tried that make key and certificate on AWS IoT web console.
And then I copied files to Raspberry Pi.
also attached policy & thing using web console.

At result...
Working well!! :)

**Comment by beomseoklee** [comment]
@nbc-pet-task I'm sorry for your inconvenience. I think [the implementation guide](https://docs.aws.amazon.com/solutions/latest/smart-product-solution/deployment.html) one step to change ```HOSTNAME``` to the actual AWS IoT endpoint in ```config.js``` file.

```bash
sed -i -e 's/HOSTNAME/'$HOST'/' config.js
```

```HOST``` can be a1inzd61czlz6f-ats.iot.us-east-1.amazonaws.com in your case.
I'm happy that you succeeded to connect to the simulator, but I would like to make sure that you have changed host configuration.

**Comment by nbc-pet-task** [comment]
Just hard coding [host] in config.js file :)

thanks!!
